version: 2

defaults: &defaults
  working_directory: ~/hela-config-tunnckocore
  docker:
    - image: circleci/node:8

restore_modules_cache: &restore_modules_cache
  restore_cache:
    keys:
    - hela-config-tunnckocore-{{ checksum "yarn.lock" }}
    # fallback to using the latest cache if no exact match is found
    - hela-config-tunnckocore-


jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - *restore_modules_cache
      - run:
          name: Installing Dependencies
          command: yarn install
      - save_cache:
          key: hela-config-tunnckocore-{{ checksum "yarn.lock" }}
          paths: node_modules
      - run:
          name: Remove node_modules to cleanup workspace
          command: rm -rf node_modules

  test:
    <<: *defaults
    steps:
      - checkout
      - *restore_modules_cache
      - run:
          name: Running tests and checks
          command: yarn hela test --no-check
      - run:
          name: Sending test coverage to CodeCov
          command: bash <(curl -s https://codecov.io/bash)

  # build:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - *restore_modules_cache

  release:
    <<: *defaults
    steps:
      - checkout
      - *restore_modules_cache
      - run:
          name: Creating distributable files
          command: yarn hela build
      - store_artifacts:
          path: dist
          destination: hela-config-tunnckocore
      - run:
          name: Releasing and publishing
          command: yarn hela release

workflows:
  version: 2
  automated:
    jobs:
      - install
      - test:
          requires:
            - install
      # - build:
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #         only: master
      - release:
          requires:
            - test
          filters:
            branches:
              only: master
          context: org-global
